name: Run License Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@master
    with:
      packages-exclude: '^(pyklatchat|neon|tqdm|RapidFuzz|typing_extensions|urllib|setuptools|click|paramiko).*'
