# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'chat_server/version.py'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'LICENSE.md'

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets: inherit
    with:
      version_file: "chat_server/version.py"
      setup_py: "setup.py"
      publish_prerelease: True
      publish_pypi: False
      update_changelog: True
  build_and_publish_docker:
    needs: publish_alpha_release
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@master
    secrets: inherit
