# This workflow will generate a release distribution and upload it to PyPI

name: Publish Build and GitHub Release
on:
  push:
    branches:
      - master

jobs:
  tag_release:
    runs-on: ${{inputs.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.VERSION}}
  build_and_publish_docker:
    uses: neongeckocom/.github/.github/workflows/publish_docker.yml@master
    secrets: inherit
